# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElectroluxTest' do
pod 'Kingfisher', '~> 7.0'
pod 'Toaster'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElectroluxTest

  target 'ElectroluxTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElectroluxTestUITests' do
    # Pods for testing
  end

end